// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cVVersionOwnedByUser = `-- name: CVVersionOwnedByUser :one
SELECT EXISTS (
    SELECT 1 FROM cv_versions WHERE id = $1 AND user_id = $2
) AS owned
`

type CVVersionOwnedByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// A cheap pre-check so the service can tell an unowned/missing cv_version_id
// apart from an unowned/missing site_id before either reaches the atomic
// INSERT/UPDATE guard, which cannot distinguish the two once it collapses to
// "no rows written". This query exists purely for that distinguishable error
// message; the INSERT/UPDATE guards remain the actual enforcement against a
// race between this check and the write.
func (q *Queries) CVVersionOwnedByUser(ctx context.Context, arg CVVersionOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, cVVersionOwnedByUser, arg.ID, arg.UserID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const createApplication = `-- name: CreateApplication :one

INSERT INTO applications (
    id, user_id, company_name, job_title, job_description, job_url,
    site_id, cv_version_id, status, applied_at
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
WHERE EXISTS (
    SELECT 1 FROM sites AS chk_site
    WHERE chk_site.id = $7 AND (chk_site.user_id IS NULL OR chk_site.user_id = $2)
)
AND ($8::uuid IS NULL OR EXISTS (
    SELECT 1 FROM cv_versions AS chk_cv
    WHERE chk_cv.id = $8 AND chk_cv.user_id = $2
))
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id
`

type CreateApplicationParams struct {
	ID             uuid.UUID         `json:"id"`
	UserID         uuid.UUID         `json:"user_id"`
	CompanyName    string            `json:"company_name"`
	JobTitle       string            `json:"job_title"`
	JobDescription string            `json:"job_description"`
	JobUrl         string            `json:"job_url"`
	SiteID         uuid.UUID         `json:"site_id"`
	CvVersionID    *uuid.UUID        `json:"cv_version_id"`
	Status         ApplicationStatus `json:"status"`
	AppliedAt      *time.Time        `json:"applied_at"`
}

// Queries for the applications module.
//
// Phase 15: every statement is now scoped by user_id — either as a WHERE clause
// on an existing row, or as a column on a new one. The one exception is
// ResolveSiteByDomain, which matches a global (user_id IS NULL) site OR one the
// caller owns, because a pre-configured site belongs to everyone.
// Both WHERE EXISTS clauses are load-bearing, not decorative: site_id and
// cv_version_id are foreign keys, and a foreign key only proves the row
// exists — it says nothing about who owns it. site_id must be global
// (user_id IS NULL) or the caller's own, matching every other site read in
// this codebase. cv_version_id is nullable — no CV attached is always fine —
// but when it is set, it must belong to this user; skip that check and one
// user's application can end up pointing at another user's CV, which is a
// worse leak than a rejected save.
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.UserID,
		arg.CompanyName,
		arg.JobTitle,
		arg.JobDescription,
		arg.JobUrl,
		arg.SiteID,
		arg.CvVersionID,
		arg.Status,
		arg.AppliedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const createApplicationStatusHistory = `-- name: CreateApplicationStatusHistory :one
INSERT INTO application_status_history (
    application_id, user_id, from_status, to_status, changed_by, note
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, application_id, from_status, to_status, changed_by, note, changed_at, user_id
`

type CreateApplicationStatusHistoryParams struct {
	ApplicationID uuid.UUID          `json:"application_id"`
	UserID        uuid.UUID          `json:"user_id"`
	FromStatus    *ApplicationStatus `json:"from_status"`
	ToStatus      ApplicationStatus  `json:"to_status"`
	ChangedBy     StatusChangeSource `json:"changed_by"`
	Note          *string            `json:"note"`
}

func (q *Queries) CreateApplicationStatusHistory(ctx context.Context, arg CreateApplicationStatusHistoryParams) (ApplicationStatusHistory, error) {
	row := q.db.QueryRow(ctx, createApplicationStatusHistory,
		arg.ApplicationID,
		arg.UserID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Note,
	)
	var i ApplicationStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Note,
		&i.ChangedAt,
		&i.UserID,
	)
	return i, err
}

const createPendingFollowUpReminder = `-- name: CreatePendingFollowUpReminder :one
INSERT INTO follow_up_reminders (application_id, user_id, due_at)
VALUES ($1, $2, $3)
ON CONFLICT (application_id) WHERE sent_at IS NULL AND dismissed_at IS NULL
DO NOTHING
RETURNING id, application_id, due_at, sent_at, dismissed_at, created_at, updated_at, user_id
`

type CreatePendingFollowUpReminderParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        uuid.UUID `json:"user_id"`
	DueAt         time.Time `json:"due_at"`
}

// uq_follow_up_reminders_one_pending allows a single un-sent, un-dismissed
// reminder per application, so a re-save is a no-op rather than an error. The
// constraint stays scoped by application_id alone (000015's reasoning: an
// application already belongs to exactly one user), so user_id here is a
// column to fill in, not part of what makes a reminder unique.
func (q *Queries) CreatePendingFollowUpReminder(ctx context.Context, arg CreatePendingFollowUpReminderParams) (FollowUpReminder, error) {
	row := q.db.QueryRow(ctx, createPendingFollowUpReminder, arg.ApplicationID, arg.UserID, arg.DueAt)
	var i FollowUpReminder
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DueAt,
		&i.SentAt,
		&i.DismissedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :execrows
DELETE FROM applications WHERE applications.id = $1 AND applications.user_id = $2
`

type DeleteApplicationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Cover letters, status history, reminders and recruiter contacts go with it via
// ON DELETE CASCADE.
func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplication, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissPendingFollowUpReminders = `-- name: DismissPendingFollowUpReminders :exec
UPDATE follow_up_reminders
SET dismissed_at = now()
WHERE application_id = $1
  AND user_id = $2
  AND sent_at IS NULL
  AND dismissed_at IS NULL
`

type DismissPendingFollowUpRemindersParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        uuid.UUID `json:"user_id"`
}

// Called when an application moves off Applied: the company (or the user) has
// moved it on, so there is nothing left to chase. user_id is redundant with
// application_id ownership already established by the caller, but it costs
// nothing to assert here too.
func (q *Queries) DismissPendingFollowUpReminders(ctx context.Context, arg DismissPendingFollowUpRemindersParams) error {
	_, err := q.db.Exec(ctx, dismissPendingFollowUpReminders, arg.ApplicationID, arg.UserID)
	return err
}

const findApplicationsByCompanyName = `-- name: FindApplicationsByCompanyName :many
SELECT id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id FROM applications
WHERE user_id = $1
  AND lower(btrim(company_name)) = lower(btrim($2::text))
ORDER BY COALESCE(applied_at, created_at) DESC
`

type FindApplicationsByCompanyNameParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CompanyName string    `json:"company_name"`
}

// The MVP duplicate check: exact company name, ignoring case and surrounding
// whitespace, scoped to the caller — someone else applying to the same company
// is not this user's duplicate.
func (q *Queries) FindApplicationsByCompanyName(ctx context.Context, arg FindApplicationsByCompanyNameParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, findApplicationsByCompanyName, arg.UserID, arg.CompanyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.JobTitle,
			&i.JobDescription,
			&i.JobUrl,
			&i.SiteID,
			&i.CvVersionID,
			&i.Status,
			&i.AiScore,
			&i.AiScoreExplanation,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSiteByID = `-- name: FindSiteByID :one
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id FROM sites
WHERE id = $1 AND (user_id IS NULL OR user_id = $2::uuid)
`

type FindSiteByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Validates a client-supplied site_id before it is trusted: global (user_id IS
// NULL) or the caller's own. Without this, resolveSiteID would accept any
// site_id the caller sent — including one belonging to somebody else — since
// the column only exists to be trusted, not verified, once it reaches the
// insert. Mirrors ResolveSiteByDomain's same-scope reasoning, keyed by id
// instead of domain.
func (q *Queries) FindSiteByID(ctx context.Context, arg FindSiteByIDParams) (Site, error) {
	row := q.db.QueryRow(ctx, findSiteByID, arg.ID, arg.UserID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id FROM applications WHERE applications.id = $1 AND applications.user_id = $2
`

type GetApplicationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.ID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listApplicationStatusHistory = `-- name: ListApplicationStatusHistory :many
SELECT id, application_id, from_status, to_status, changed_by, note, changed_at, user_id FROM application_status_history
WHERE application_id = $1 AND user_id = $2
ORDER BY changed_at ASC
`

type ListApplicationStatusHistoryParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) ListApplicationStatusHistory(ctx context.Context, arg ListApplicationStatusHistoryParams) ([]ApplicationStatusHistory, error) {
	rows, err := q.db.Query(ctx, listApplicationStatusHistory, arg.ApplicationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationStatusHistory{}
	for rows.Next() {
		var i ApplicationStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Note,
			&i.ChangedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id FROM applications
WHERE user_id = $1
  AND ($2::application_status IS NULL OR status = $2::application_status)
  AND ($3::uuid IS NULL OR site_id = $3::uuid)
  AND ($4::uuid IS NULL OR cv_version_id = $4::uuid)
  AND ($5::text IS NULL
       OR company_name ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL
       OR company_name ILIKE '%' || $6::text || '%'
       OR job_title ILIKE '%' || $6::text || '%')
  AND ($7::timestamptz IS NULL
       OR COALESCE(applied_at, created_at) >= $7::timestamptz)
  AND ($8::timestamptz IS NULL
       OR COALESCE(applied_at, created_at) <= $8::timestamptz)
ORDER BY COALESCE(applied_at, created_at) DESC, created_at DESC
LIMIT $10::int OFFSET $9::int
`

type ListApplicationsParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	Status      *ApplicationStatus `json:"status"`
	SiteID      *uuid.UUID         `json:"site_id"`
	CvVersionID *uuid.UUID         `json:"cv_version_id"`
	Company     *string            `json:"company"`
	Search      *string            `json:"search"`
	FromDate    *time.Time         `json:"from_date"`
	ToDate      *time.Time         `json:"to_date"`
	RowOffset   int32              `json:"row_offset"`
	RowLimit    int32              `json:"row_limit"`
}

// Every filter is optional: a NULL parameter disables that clause. Ordering and
// date filtering both use the effective date — applied_at when set, created_at
// otherwise — so a Saved application is never invisible to a date range.
func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications,
		arg.UserID,
		arg.Status,
		arg.SiteID,
		arg.CvVersionID,
		arg.Company,
		arg.Search,
		arg.FromDate,
		arg.ToDate,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.JobTitle,
			&i.JobDescription,
			&i.JobUrl,
			&i.SiteID,
			&i.CvVersionID,
			&i.Status,
			&i.AiScore,
			&i.AiScoreExplanation,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSiteByDomain = `-- name: ResolveSiteByDomain :one
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id FROM sites
WHERE is_active = true
  AND regexp_replace(lower(btrim(domain)), '^www\.', '') = $1::text
  AND (user_id IS NULL OR user_id = $2::uuid)
LIMIT 1
`

type ResolveSiteByDomainParams struct {
	Domain string    `json:"domain"`
	UserID uuid.UUID `json:"user_id"`
}

// Turns a job URL host into a site_id when the client did not send one.
//
// Matches a global site (user_id IS NULL — the pre-configured list every user
// sees) or one the caller registered themselves. Without the second half of
// that OR, a user's own custom site could never be resolved from a job URL,
// only from an explicit site_id.
//
// The service passes a lowercased, www-stripped host, so the stored value is
// normalised the same way here: "www.LinkedIn.com" and "linkedin.com" both match.
func (q *Queries) ResolveSiteByDomain(ctx context.Context, arg ResolveSiteByDomainParams) (Site, error) {
	row := q.db.QueryRow(ctx, resolveSiteByDomain, arg.Domain, arg.UserID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const setApplicationAIScore = `-- name: SetApplicationAIScore :one
UPDATE applications
SET ai_score             = $1,
    ai_score_explanation = $2,
    updated_at           = now()
WHERE applications.id = $3 AND applications.user_id = $4
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id
`

type SetApplicationAIScoreParams struct {
	AiScore            *float64  `json:"ai_score"`
	AiScoreExplanation *string   `json:"ai_score_explanation"`
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
}

// Writes the GPT-4o-mini job-match score. Called inside the same transaction as
// CreateApplication (Flow 1 step 23), and available on its own as the retry path
// for an application saved while scoring was unavailable.
func (q *Queries) SetApplicationAIScore(ctx context.Context, arg SetApplicationAIScoreParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationAIScore,
		arg.AiScore,
		arg.AiScoreExplanation,
		arg.ID,
		arg.UserID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET company_name    = $2,
    job_title       = $3,
    job_description = $4,
    job_url         = $5,
    site_id         = $6,
    cv_version_id   = $7
WHERE applications.id = $1
  AND applications.user_id = $8
  AND EXISTS (
      SELECT 1 FROM sites AS chk_site
      WHERE chk_site.id = $6 AND (chk_site.user_id IS NULL OR chk_site.user_id = $8)
  )
  AND ($7::uuid IS NULL OR EXISTS (
      SELECT 1 FROM cv_versions AS chk_cv
      WHERE chk_cv.id = $7 AND chk_cv.user_id = $8
  ))
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id
`

type UpdateApplicationParams struct {
	ID             uuid.UUID  `json:"id"`
	CompanyName    string     `json:"company_name"`
	JobTitle       string     `json:"job_title"`
	JobDescription string     `json:"job_description"`
	JobUrl         string     `json:"job_url"`
	SiteID         uuid.UUID  `json:"site_id"`
	CvVersionID    *uuid.UUID `json:"cv_version_id"`
	UserID         uuid.UUID  `json:"user_id"`
}

// Captured job data only. Status never moves here — that is
// UpdateApplicationStatus, so no transition can skip the audit trail.
//
// Same ownership guards as CreateApplication, for the same reason: this is
// also the query Complete uses to attach a CV version (Flow 2), so the check
// has to live here too, not only on the insert path.
func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.CompanyName,
		arg.JobTitle,
		arg.JobDescription,
		arg.JobUrl,
		arg.SiteID,
		arg.CvVersionID,
		arg.UserID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status     = $1,
    applied_at = COALESCE(applications.applied_at, $2::timestamptz)
WHERE applications.id = $3 AND applications.user_id = $4
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at, user_id
`

type UpdateApplicationStatusParams struct {
	Status    ApplicationStatus `json:"status"`
	AppliedAt *time.Time        `json:"applied_at"`
	ID        uuid.UUID         `json:"id"`
	UserID    uuid.UUID         `json:"user_id"`
}

// applied_at is write-once: COALESCE keeps the original timestamp if the
// application has already been applied to, so bouncing through statuses later
// never rewrites when it was actually sent.
func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus,
		arg.Status,
		arg.AppliedAt,
		arg.ID,
		arg.UserID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
