// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one

INSERT INTO applications (
    id, company_name, job_title, job_description, job_url,
    site_id, cv_version_id, status, applied_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at
`

type CreateApplicationParams struct {
	ID             uuid.UUID         `json:"id"`
	CompanyName    string            `json:"company_name"`
	JobTitle       string            `json:"job_title"`
	JobDescription string            `json:"job_description"`
	JobUrl         string            `json:"job_url"`
	SiteID         uuid.UUID         `json:"site_id"`
	CvVersionID    *uuid.UUID        `json:"cv_version_id"`
	Status         ApplicationStatus `json:"status"`
	AppliedAt      *time.Time        `json:"applied_at"`
}

// Queries for the applications module. Run `sqlc generate` after adding this
// file; internal/db/sqlc/applications.sql.go and the additions to querier.go are
// generated from it.
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.CompanyName,
		arg.JobTitle,
		arg.JobDescription,
		arg.JobUrl,
		arg.SiteID,
		arg.CvVersionID,
		arg.Status,
		arg.AppliedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplicationStatusHistory = `-- name: CreateApplicationStatusHistory :one
INSERT INTO application_status_history (
    application_id, from_status, to_status, changed_by, note
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, application_id, from_status, to_status, changed_by, note, changed_at
`

type CreateApplicationStatusHistoryParams struct {
	ApplicationID uuid.UUID          `json:"application_id"`
	FromStatus    *ApplicationStatus `json:"from_status"`
	ToStatus      ApplicationStatus  `json:"to_status"`
	ChangedBy     StatusChangeSource `json:"changed_by"`
	Note          *string            `json:"note"`
}

func (q *Queries) CreateApplicationStatusHistory(ctx context.Context, arg CreateApplicationStatusHistoryParams) (ApplicationStatusHistory, error) {
	row := q.db.QueryRow(ctx, createApplicationStatusHistory,
		arg.ApplicationID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Note,
	)
	var i ApplicationStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Note,
		&i.ChangedAt,
	)
	return i, err
}

const createPendingFollowUpReminder = `-- name: CreatePendingFollowUpReminder :one
INSERT INTO follow_up_reminders (application_id, due_at)
VALUES ($1, $2)
ON CONFLICT (application_id) WHERE sent_at IS NULL AND dismissed_at IS NULL
DO NOTHING
RETURNING id, application_id, due_at, sent_at, dismissed_at, created_at, updated_at
`

type CreatePendingFollowUpReminderParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	DueAt         time.Time `json:"due_at"`
}

// uq_follow_up_reminders_one_pending allows a single un-sent, un-dismissed
// reminder per application, so a re-save is a no-op rather than an error.
func (q *Queries) CreatePendingFollowUpReminder(ctx context.Context, arg CreatePendingFollowUpReminderParams) (FollowUpReminder, error) {
	row := q.db.QueryRow(ctx, createPendingFollowUpReminder, arg.ApplicationID, arg.DueAt)
	var i FollowUpReminder
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DueAt,
		&i.SentAt,
		&i.DismissedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :execrows
DELETE FROM applications WHERE id = $1
`

// Cover letters, status history, reminders and recruiter contacts go with it via
// ON DELETE CASCADE.
func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplication, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissPendingFollowUpReminders = `-- name: DismissPendingFollowUpReminders :exec
UPDATE follow_up_reminders
SET dismissed_at = now()
WHERE application_id = $1
  AND sent_at IS NULL
  AND dismissed_at IS NULL
`

// Called when an application moves off Applied: the company (or the user) has
// moved it on, so there is nothing left to chase.
func (q *Queries) DismissPendingFollowUpReminders(ctx context.Context, applicationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dismissPendingFollowUpReminders, applicationID)
	return err
}

const findApplicationsByCompanyName = `-- name: FindApplicationsByCompanyName :many
SELECT id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at FROM applications
WHERE lower(btrim(company_name)) = lower(btrim($1::text))
ORDER BY COALESCE(applied_at, created_at) DESC
`

// The MVP duplicate check: exact company name, ignoring case and surrounding
// whitespace. Embedding similarity is a later phase.
func (q *Queries) FindApplicationsByCompanyName(ctx context.Context, companyName string) ([]Application, error) {
	rows, err := q.db.Query(ctx, findApplicationsByCompanyName, companyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.JobTitle,
			&i.JobDescription,
			&i.JobUrl,
			&i.SiteID,
			&i.CvVersionID,
			&i.Status,
			&i.AiScore,
			&i.AiScoreExplanation,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplication = `-- name: GetApplication :one
SELECT id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationStatusHistory = `-- name: ListApplicationStatusHistory :many
SELECT id, application_id, from_status, to_status, changed_by, note, changed_at FROM application_status_history
WHERE application_id = $1
ORDER BY changed_at ASC
`

func (q *Queries) ListApplicationStatusHistory(ctx context.Context, applicationID uuid.UUID) ([]ApplicationStatusHistory, error) {
	rows, err := q.db.Query(ctx, listApplicationStatusHistory, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationStatusHistory{}
	for rows.Next() {
		var i ApplicationStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Note,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at FROM applications
WHERE ($1::application_status IS NULL OR status = $1::application_status)
  AND ($2::uuid IS NULL OR site_id = $2::uuid)
  AND ($3::uuid IS NULL OR cv_version_id = $3::uuid)
  AND ($4::text IS NULL
       OR company_name ILIKE '%' || $4::text || '%')
  AND ($5::text IS NULL
       OR company_name ILIKE '%' || $5::text || '%'
       OR job_title ILIKE '%' || $5::text || '%')
  AND ($6::timestamptz IS NULL
       OR COALESCE(applied_at, created_at) >= $6::timestamptz)
  AND ($7::timestamptz IS NULL
       OR COALESCE(applied_at, created_at) <= $7::timestamptz)
ORDER BY COALESCE(applied_at, created_at) DESC, created_at DESC
LIMIT $9::int OFFSET $8::int
`

type ListApplicationsParams struct {
	Status      *ApplicationStatus `json:"status"`
	SiteID      *uuid.UUID         `json:"site_id"`
	CvVersionID *uuid.UUID         `json:"cv_version_id"`
	Company     *string            `json:"company"`
	Search      *string            `json:"search"`
	FromDate    *time.Time         `json:"from_date"`
	ToDate      *time.Time         `json:"to_date"`
	RowOffset   int32              `json:"row_offset"`
	RowLimit    int32              `json:"row_limit"`
}

// Every filter is optional: a NULL parameter disables that clause. Ordering and
// date filtering both use the effective date — applied_at when set, created_at
// otherwise — so a Saved application is never invisible to a date range.
func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications,
		arg.Status,
		arg.SiteID,
		arg.CvVersionID,
		arg.Company,
		arg.Search,
		arg.FromDate,
		arg.ToDate,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.JobTitle,
			&i.JobDescription,
			&i.JobUrl,
			&i.SiteID,
			&i.CvVersionID,
			&i.Status,
			&i.AiScore,
			&i.AiScoreExplanation,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSiteByDomain = `-- name: ResolveSiteByDomain :one
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at FROM sites
WHERE is_active = true
  AND regexp_replace(lower(btrim(domain)), '^www\.', '') = $1::text
LIMIT 1
`

// Turns a job URL host into a site_id when the client did not send one.
// NOTE: if queries/sites.sql already defines an equivalent lookup, delete this
// one and point the repository at that generated method instead — two queries
// with the same name in the same package will not compile.
//
// The service passes a lowercased, www-stripped host, so the stored value is
// normalised the same way here: "www.LinkedIn.com" and "linkedin.com" both match.
func (q *Queries) ResolveSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRow(ctx, resolveSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET company_name    = $2,
    job_title       = $3,
    job_description = $4,
    job_url         = $5,
    site_id         = $6,
    cv_version_id   = $7
WHERE id = $1
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID             uuid.UUID  `json:"id"`
	CompanyName    string     `json:"company_name"`
	JobTitle       string     `json:"job_title"`
	JobDescription string     `json:"job_description"`
	JobUrl         string     `json:"job_url"`
	SiteID         uuid.UUID  `json:"site_id"`
	CvVersionID    *uuid.UUID `json:"cv_version_id"`
}

// Captured job data only. Status never moves here — that is
// UpdateApplicationStatus, so no transition can skip the audit trail.
func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.CompanyName,
		arg.JobTitle,
		arg.JobDescription,
		arg.JobUrl,
		arg.SiteID,
		arg.CvVersionID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status     = $1,
    applied_at = COALESCE(applications.applied_at, $2::timestamptz)
WHERE id = $3
RETURNING id, company_name, job_title, job_description, job_url, site_id, cv_version_id, status, ai_score, ai_score_explanation, applied_at, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	Status    ApplicationStatus `json:"status"`
	AppliedAt *time.Time        `json:"applied_at"`
	ID        uuid.UUID         `json:"id"`
}

// applied_at is write-once: COALESCE keeps the original timestamp if the
// application has already been applied to, so bouncing through statuses later
// never rewrites when it was actually sent.
func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus, arg.Status, arg.AppliedAt, arg.ID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.JobTitle,
		&i.JobDescription,
		&i.JobUrl,
		&i.SiteID,
		&i.CvVersionID,
		&i.Status,
		&i.AiScore,
		&i.AiScoreExplanation,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
