// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, token_hash, name, is_read_only)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, name, last_used_at, revoked_at, created_at, is_read_only
`

type CreateAPITokenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	Name       string    `json:"name"`
	IsReadOnly bool      `json:"is_read_only"`
}

// ---------------------------------------------------------------------------
// API tokens
// ---------------------------------------------------------------------------
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.TokenHash,
		arg.Name,
		arg.IsReadOnly,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.IsReadOnly,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, expires_at, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	UserAgent *string     `json:"user_agent"`
	IpAddress *netip.Addr `json:"ip_address"`
}

// ---------------------------------------------------------------------------
// Sessions
// ---------------------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, display_name, email_verified_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     *string    `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

// Queries for the auth module.
//
// Neither sessions nor api_tokens is ever looked up by its raw token. The
// client holds the raw value; this stores only its SHA-256, and every lookup
// hashes what arrived before searching. A dump of this database yields no
// usable credentials.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < now() - interval '30 days'
`

// Housekeeping, not authentication: expired rows are already unusable because
// every lookup filters them out. This only stops the table growing forever.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendSession = `-- name: ExtendSession :one
UPDATE sessions
SET expires_at = $2
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, created_at
`

type ExtendSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// The sliding half of the 30-day window. Called only when the service decides
// enough time has passed to be worth a write.
func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, extendSession, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const findLiveAPITokenByTokenHash = `-- name: FindLiveAPITokenByTokenHash :one
SELECT id, user_id, token_hash, name, last_used_at, revoked_at, created_at, is_read_only FROM api_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
`

// No expiry column: an API token lives until it is revoked. That is deliberate
// — the extension cannot prompt for a re-login, so a token that silently
// expired would look like the extension breaking.
func (q *Queries) FindLiveAPITokenByTokenHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, findLiveAPITokenByTokenHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.IsReadOnly,
	)
	return i, err
}

const findLiveSessionByTokenHash = `-- name: FindLiveSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, created_at FROM sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

// The hot path: every authenticated dashboard request runs this. Expiry and
// revocation are filtered here rather than in Go so that a stale row can never
// be authenticated by a caller that forgot to check.
func (q *Queries) FindLiveSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, findLiveSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, display_name, email_verified_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, email_verified_at, created_at, updated_at FROM users WHERE email = $1
`

// email is citext, so this is already case-insensitive at the database level.
// The service normalises anyway, so the two never disagree about what "the same
// address" means.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAPITokens = `-- name: ListActiveAPITokens :many
SELECT id, user_id, token_hash, name, last_used_at, revoked_at, created_at, is_read_only FROM api_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAPITokens(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listActiveAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Name,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.IsReadOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, created_at FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// "Sign out everywhere". Also the correct response to a password change.
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Scoped by user_id as well as id: a session id is a uuid the caller could have
// obtained anywhere, and revoking somebody else's session is not a feature.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

// Logout. The caller presents a token rather than an id.
func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens
SET last_used_at = now()
WHERE id = $1
`

// Best-effort, called after a successful match. A failure here must never fail
// the request it was authenticating.
func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, email, password_hash, display_name, email_verified_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
