// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cover_letters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCoverLetter = `-- name: CreateCoverLetter :one

INSERT INTO cover_letters (
    id,
    application_id,
    kind,
    body_text,
    s3_key,
    original_filename
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, kind, body_text, s3_key, original_filename, created_at, updated_at
`

type CreateCoverLetterParams struct {
	ID               uuid.UUID       `json:"id"`
	ApplicationID    uuid.UUID       `json:"application_id"`
	Kind             CoverLetterKind `json:"kind"`
	BodyText         *string         `json:"body_text"`
	S3Key            *string         `json:"s3_key"`
	OriginalFilename *string         `json:"original_filename"`
}

// Queries for the coverletters module.
//
// cover_letters is one-to-one with applications (unique(application_id)), so
// every statement here is keyed by application_id rather than by the row's own
// id. There is no history table and nothing to match against.
// The id is supplied by the service rather than defaulted, because a file
// cover letter's S3 key is derived from it before the row is written.
func (q *Queries) CreateCoverLetter(ctx context.Context, arg CreateCoverLetterParams) (CoverLetter, error) {
	row := q.db.QueryRow(ctx, createCoverLetter,
		arg.ID,
		arg.ApplicationID,
		arg.Kind,
		arg.BodyText,
		arg.S3Key,
		arg.OriginalFilename,
	)
	var i CoverLetter
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.BodyText,
		&i.S3Key,
		&i.OriginalFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoverLetterByApplicationID = `-- name: DeleteCoverLetterByApplicationID :exec
DELETE
FROM cover_letters
WHERE application_id = $1
`

// Used to implement replace-on-save. Deleting a row that is not there is a
// no-op, which is what the service relies on.
func (q *Queries) DeleteCoverLetterByApplicationID(ctx context.Context, applicationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoverLetterByApplicationID, applicationID)
	return err
}

const getCoverLetterByApplicationID = `-- name: GetCoverLetterByApplicationID :one
SELECT id, application_id, kind, body_text, s3_key, original_filename, created_at, updated_at
FROM cover_letters
WHERE application_id = $1
`

func (q *Queries) GetCoverLetterByApplicationID(ctx context.Context, applicationID uuid.UUID) (CoverLetter, error) {
	row := q.db.QueryRow(ctx, getCoverLetterByApplicationID, applicationID)
	var i CoverLetter
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.BodyText,
		&i.S3Key,
		&i.OriginalFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCoverLetterText = `-- name: UpdateCoverLetterText :one
UPDATE cover_letters
SET body_text  = $2,
    updated_at = now()
WHERE application_id = $1
  AND kind = 'text'
RETURNING id, application_id, kind, body_text, s3_key, original_filename, created_at, updated_at
`

type UpdateCoverLetterTextParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	BodyText      *string   `json:"body_text"`
}

// Scoped to kind = 'text'. A file cover letter records the bytes that were
// actually sent and is immutable; without this predicate the row-level check
// constraint would reject the write anyway, but with a far less useful error.
func (q *Queries) UpdateCoverLetterText(ctx context.Context, arg UpdateCoverLetterTextParams) (CoverLetter, error) {
	row := q.db.QueryRow(ctx, updateCoverLetterText, arg.ApplicationID, arg.BodyText)
	var i CoverLetter
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.BodyText,
		&i.S3Key,
		&i.OriginalFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
