// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cvs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCV = `-- name: CreateCV :one

INSERT INTO cvs (name, tag)
VALUES ($1, $2)
RETURNING id, name, tag, created_at, updated_at
`

type CreateCVParams struct {
	Name string  `json:"name"`
	Tag  *string `json:"tag"`
}

// ApplyMind — cvs module queries
//
// Note: application status is cast to text so this module does not depend on the
// generated enum type from the applications module.
func (q *Queries) CreateCV(ctx context.Context, arg CreateCVParams) (Cv, error) {
	row := q.db.QueryRow(ctx, createCV, arg.Name, arg.Tag)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCVVersion = `-- name: CreateCVVersion :one
INSERT INTO cv_versions (id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at
`

type CreateCVVersionParams struct {
	ID               uuid.UUID `json:"id"`
	CvID             uuid.UUID `json:"cv_id"`
	Sha256Hash       string    `json:"sha256_hash"`
	FileSizeBytes    int64     `json:"file_size_bytes"`
	OriginalFilename string    `json:"original_filename"`
	S3Key            string    `json:"s3_key"`
}

func (q *Queries) CreateCVVersion(ctx context.Context, arg CreateCVVersionParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, createCVVersion,
		arg.ID,
		arg.CvID,
		arg.Sha256Hash,
		arg.FileSizeBytes,
		arg.OriginalFilename,
		arg.S3Key,
	)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.CvID,
		&i.Sha256Hash,
		&i.FileSizeBytes,
		&i.OriginalFilename,
		&i.S3Key,
		&i.UploadedAt,
	)
	return i, err
}

const deleteCV = `-- name: DeleteCV :exec
DELETE FROM cvs WHERE id = $1
`

func (q *Queries) DeleteCV(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCV, id)
	return err
}

const findCVVersionByCVAndHash = `-- name: FindCVVersionByCVAndHash :one
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions
WHERE cv_id = $1 AND sha256_hash = $2
LIMIT 1
`

type FindCVVersionByCVAndHashParams struct {
	CvID       uuid.UUID `json:"cv_id"`
	Sha256Hash string    `json:"sha256_hash"`
}

func (q *Queries) FindCVVersionByCVAndHash(ctx context.Context, arg FindCVVersionByCVAndHashParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, findCVVersionByCVAndHash, arg.CvID, arg.Sha256Hash)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.CvID,
		&i.Sha256Hash,
		&i.FileSizeBytes,
		&i.OriginalFilename,
		&i.S3Key,
		&i.UploadedAt,
	)
	return i, err
}

const findCVVersionByCVAndSize = `-- name: FindCVVersionByCVAndSize :one
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions
WHERE cv_id = $1 AND file_size_bytes = $2
ORDER BY uploaded_at DESC
LIMIT 1
`

type FindCVVersionByCVAndSizeParams struct {
	CvID          uuid.UUID `json:"cv_id"`
	FileSizeBytes int64     `json:"file_size_bytes"`
}

func (q *Queries) FindCVVersionByCVAndSize(ctx context.Context, arg FindCVVersionByCVAndSizeParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, findCVVersionByCVAndSize, arg.CvID, arg.FileSizeBytes)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.CvID,
		&i.Sha256Hash,
		&i.FileSizeBytes,
		&i.OriginalFilename,
		&i.S3Key,
		&i.UploadedAt,
	)
	return i, err
}

const findCVVersionByHash = `-- name: FindCVVersionByHash :one
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions
WHERE sha256_hash = $1
ORDER BY uploaded_at DESC
LIMIT 1
`

func (q *Queries) FindCVVersionByHash(ctx context.Context, sha256Hash string) (CvVersion, error) {
	row := q.db.QueryRow(ctx, findCVVersionByHash, sha256Hash)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.CvID,
		&i.Sha256Hash,
		&i.FileSizeBytes,
		&i.OriginalFilename,
		&i.S3Key,
		&i.UploadedAt,
	)
	return i, err
}

const findLatestCVVersionByFilename = `-- name: FindLatestCVVersionByFilename :one
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions
WHERE original_filename = $1
ORDER BY uploaded_at DESC
LIMIT 1
`

func (q *Queries) FindLatestCVVersionByFilename(ctx context.Context, originalFilename string) (CvVersion, error) {
	row := q.db.QueryRow(ctx, findLatestCVVersionByFilename, originalFilename)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.CvID,
		&i.Sha256Hash,
		&i.FileSizeBytes,
		&i.OriginalFilename,
		&i.S3Key,
		&i.UploadedAt,
	)
	return i, err
}

const getCV = `-- name: GetCV :one
SELECT id, name, tag, created_at, updated_at FROM cvs WHERE id = $1
`

func (q *Queries) GetCV(ctx context.Context, id uuid.UUID) (Cv, error) {
	row := q.db.QueryRow(ctx, getCV, id)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVByName = `-- name: GetCVByName :one
SELECT id, name, tag, created_at, updated_at FROM cvs WHERE name = $1
`

func (q *Queries) GetCVByName(ctx context.Context, name string) (Cv, error) {
	row := q.db.QueryRow(ctx, getCVByName, name)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVVersion = `-- name: GetCVVersion :one
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions WHERE id = $1
`

func (q *Queries) GetCVVersion(ctx context.Context, id uuid.UUID) (CvVersion, error) {
	row := q.db.QueryRow(ctx, getCVVersion, id)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.CvID,
		&i.Sha256Hash,
		&i.FileSizeBytes,
		&i.OriginalFilename,
		&i.S3Key,
		&i.UploadedAt,
	)
	return i, err
}

const getLastCVUsage = `-- name: GetLastCVUsage :one
SELECT
    a.company_name,
    a.applied_at
FROM applications a
JOIN cv_versions v ON v.id = a.cv_version_id
WHERE v.cv_id = $1 AND a.applied_at IS NOT NULL
ORDER BY a.applied_at DESC
LIMIT 1
`

type GetLastCVUsageRow struct {
	CompanyName string     `json:"company_name"`
	AppliedAt   *time.Time `json:"applied_at"`
}

func (q *Queries) GetLastCVUsage(ctx context.Context, cvID uuid.UUID) (GetLastCVUsageRow, error) {
	row := q.db.QueryRow(ctx, getLastCVUsage, cvID)
	var i GetLastCVUsageRow
	err := row.Scan(&i.CompanyName, &i.AppliedAt)
	return i, err
}

const listAllCVVersions = `-- name: ListAllCVVersions :many
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions
ORDER BY cv_id, uploaded_at DESC
`

func (q *Queries) ListAllCVVersions(ctx context.Context) ([]CvVersion, error) {
	rows, err := q.db.Query(ctx, listAllCVVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CvVersion{}
	for rows.Next() {
		var i CvVersion
		if err := rows.Scan(
			&i.ID,
			&i.CvID,
			&i.Sha256Hash,
			&i.FileSizeBytes,
			&i.OriginalFilename,
			&i.S3Key,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsUsingCVVersion = `-- name: ListApplicationsUsingCVVersion :many
SELECT
    a.id,
    a.company_name,
    a.job_title,
    a.status::text AS status,
    a.applied_at
FROM applications a
WHERE a.cv_version_id = $1
ORDER BY a.applied_at DESC NULLS LAST
`

type ListApplicationsUsingCVVersionRow struct {
	ID          uuid.UUID  `json:"id"`
	CompanyName string     `json:"company_name"`
	JobTitle    string     `json:"job_title"`
	Status      string     `json:"status"`
	AppliedAt   *time.Time `json:"applied_at"`
}

func (q *Queries) ListApplicationsUsingCVVersion(ctx context.Context, cvVersionID *uuid.UUID) ([]ListApplicationsUsingCVVersionRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsUsingCVVersion, cvVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsUsingCVVersionRow{}
	for rows.Next() {
		var i ListApplicationsUsingCVVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.JobTitle,
			&i.Status,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVs = `-- name: ListCVs :many
SELECT id, name, tag, created_at, updated_at FROM cvs ORDER BY created_at DESC
`

func (q *Queries) ListCVs(ctx context.Context) ([]Cv, error) {
	rows, err := q.db.Query(ctx, listCVs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cv{}
	for rows.Next() {
		var i Cv
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsForCV = `-- name: ListVersionsForCV :many
SELECT id, cv_id, sha256_hash, file_size_bytes, original_filename, s3_key, uploaded_at FROM cv_versions
WHERE cv_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListVersionsForCV(ctx context.Context, cvID uuid.UUID) ([]CvVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsForCV, cvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CvVersion{}
	for rows.Next() {
		var i CvVersion
		if err := rows.Scan(
			&i.ID,
			&i.CvID,
			&i.Sha256Hash,
			&i.FileSizeBytes,
			&i.OriginalFilename,
			&i.S3Key,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
