// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ApplicationStatus string

const (
	ApplicationStatusSaved              ApplicationStatus = "Saved"
	ApplicationStatusInProgress         ApplicationStatus = "In Progress"
	ApplicationStatusApplied            ApplicationStatus = "Applied"
	ApplicationStatusAcknowledged       ApplicationStatus = "Acknowledged"
	ApplicationStatusInReview           ApplicationStatus = "In Review"
	ApplicationStatusInterviewScheduled ApplicationStatus = "Interview Scheduled"
	ApplicationStatusInterviewing       ApplicationStatus = "Interviewing"
	ApplicationStatusOfferReceived      ApplicationStatus = "Offer Received"
	ApplicationStatusAccepted           ApplicationStatus = "Accepted"
	ApplicationStatusRejected           ApplicationStatus = "Rejected"
	ApplicationStatusWithdrawn          ApplicationStatus = "Withdrawn"
	ApplicationStatusGhost              ApplicationStatus = "Ghost"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus `json:"application_status"`
	Valid             bool              `json:"valid"` // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type CoverLetterKind string

const (
	CoverLetterKindText CoverLetterKind = "text"
	CoverLetterKindFile CoverLetterKind = "file"
)

func (e *CoverLetterKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoverLetterKind(s)
	case string:
		*e = CoverLetterKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CoverLetterKind: %T", src)
	}
	return nil
}

type NullCoverLetterKind struct {
	CoverLetterKind CoverLetterKind `json:"cover_letter_kind"`
	Valid           bool            `json:"valid"` // Valid is true if CoverLetterKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoverLetterKind) Scan(value interface{}) error {
	if value == nil {
		ns.CoverLetterKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoverLetterKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoverLetterKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoverLetterKind), nil
}

type StatusChangeSource string

const (
	StatusChangeSourceUser   StatusChangeSource = "user"
	StatusChangeSourceSystem StatusChangeSource = "system"
)

func (e *StatusChangeSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusChangeSource(s)
	case string:
		*e = StatusChangeSource(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusChangeSource: %T", src)
	}
	return nil
}

type NullStatusChangeSource struct {
	StatusChangeSource StatusChangeSource `json:"status_change_source"`
	Valid              bool               `json:"valid"` // Valid is true if StatusChangeSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusChangeSource) Scan(value interface{}) error {
	if value == nil {
		ns.StatusChangeSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusChangeSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusChangeSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusChangeSource), nil
}

type Application struct {
	ID                 uuid.UUID         `json:"id"`
	CompanyName        string            `json:"company_name"`
	JobTitle           string            `json:"job_title"`
	JobDescription     string            `json:"job_description"`
	JobUrl             string            `json:"job_url"`
	SiteID             uuid.UUID         `json:"site_id"`
	CvVersionID        *uuid.UUID        `json:"cv_version_id"`
	Status             ApplicationStatus `json:"status"`
	AiScore            *float64          `json:"ai_score"`
	AiScoreExplanation *string           `json:"ai_score_explanation"`
	AppliedAt          *time.Time        `json:"applied_at"`
	CreatedAt          time.Time         `json:"created_at"`
	UpdatedAt          time.Time         `json:"updated_at"`
}

type ApplicationStatusHistory struct {
	ID            uuid.UUID          `json:"id"`
	ApplicationID uuid.UUID          `json:"application_id"`
	FromStatus    *ApplicationStatus `json:"from_status"`
	ToStatus      ApplicationStatus  `json:"to_status"`
	ChangedBy     StatusChangeSource `json:"changed_by"`
	Note          *string            `json:"note"`
	ChangedAt     time.Time          `json:"changed_at"`
}

type CoverLetter struct {
	ID               uuid.UUID       `json:"id"`
	ApplicationID    uuid.UUID       `json:"application_id"`
	Kind             CoverLetterKind `json:"kind"`
	BodyText         *string         `json:"body_text"`
	S3Key            *string         `json:"s3_key"`
	OriginalFilename *string         `json:"original_filename"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Cv struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Tag       *string   `json:"tag"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CvVersion struct {
	ID               uuid.UUID `json:"id"`
	CvID             uuid.UUID `json:"cv_id"`
	Sha256Hash       string    `json:"sha256_hash"`
	FileSizeBytes    int64     `json:"file_size_bytes"`
	OriginalFilename string    `json:"original_filename"`
	S3Key            string    `json:"s3_key"`
	UploadedAt       time.Time `json:"uploaded_at"`
}

type FollowUpReminder struct {
	ID            uuid.UUID  `json:"id"`
	ApplicationID uuid.UUID  `json:"application_id"`
	DueAt         time.Time  `json:"due_at"`
	SentAt        *time.Time `json:"sent_at"`
	DismissedAt   *time.Time `json:"dismissed_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type RecruiterContact struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
	Name          *string   `json:"name"`
	Email         *string   `json:"email"`
	LinkedinUrl   *string   `json:"linkedin_url"`
	Notes         *string   `json:"notes"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Setting struct {
	ID             bool      `json:"id"`
	ProfileSummary *string   `json:"profile_summary"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Site struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Domain          string    `json:"domain"`
	IsPreconfigured bool      `json:"is_preconfigured"`
	IsActive        bool      `json:"is_active"`
	Selectors       []byte    `json:"selectors"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
