// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findDueFollowUpReminders = `-- name: FindDueFollowUpReminders :many

SELECT r.id,
       r.application_id,
       r.due_at,
       r.sent_at,
       r.dismissed_at,
       r.created_at,
       r.updated_at,
       a.company_name,
       a.job_title,
       a.job_url,
       a.status,
       a.applied_at
FROM follow_up_reminders r
         JOIN applications a ON a.id = r.application_id
WHERE r.dismissed_at IS NULL
  AND r.due_at <= $1::timestamptz
  AND ($2::boolean OR r.sent_at IS NULL)
ORDER BY r.due_at ASC
`

type FindDueFollowUpRemindersParams struct {
	AsOf        time.Time `json:"as_of"`
	IncludeSent bool      `json:"include_sent"`
}

type FindDueFollowUpRemindersRow struct {
	ID            uuid.UUID         `json:"id"`
	ApplicationID uuid.UUID         `json:"application_id"`
	DueAt         time.Time         `json:"due_at"`
	SentAt        *time.Time        `json:"sent_at"`
	DismissedAt   *time.Time        `json:"dismissed_at"`
	CreatedAt     time.Time         `json:"created_at"`
	UpdatedAt     time.Time         `json:"updated_at"`
	CompanyName   string            `json:"company_name"`
	JobTitle      string            `json:"job_title"`
	JobUrl        string            `json:"job_url"`
	Status        ApplicationStatus `json:"status"`
	AppliedAt     *time.Time        `json:"applied_at"`
}

// Queries for the notifications module. Reminder *creation* and *dismissal* stay
// in queries/applications.sql: they happen during a save or a status change,
// inside that module's transaction.
// FindDueFollowUpReminders is flow 4 steps 3 and 5 collapsed into one round
// trip: the due reminders plus the application data needed to describe each one.
//
// Dismissed reminders are always excluded. @include_sent = false is the sweep
// (flow 4's sent_at IS NULL, which makes a second run on the same day a no-op);
// true is the dashboard poll, which still wants a reminder the sweep already
// dispatched this morning.
func (q *Queries) FindDueFollowUpReminders(ctx context.Context, arg FindDueFollowUpRemindersParams) ([]FindDueFollowUpRemindersRow, error) {
	rows, err := q.db.Query(ctx, findDueFollowUpReminders, arg.AsOf, arg.IncludeSent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDueFollowUpRemindersRow{}
	for rows.Next() {
		var i FindDueFollowUpRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DueAt,
			&i.SentAt,
			&i.DismissedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.JobTitle,
			&i.JobUrl,
			&i.Status,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFollowUpReminderSent = `-- name: MarkFollowUpReminderSent :one
UPDATE follow_up_reminders
SET sent_at = $1::timestamptz
WHERE id = $2
  AND sent_at IS NULL
  AND dismissed_at IS NULL
RETURNING id, application_id, due_at, sent_at, dismissed_at, created_at, updated_at, user_id
`

type MarkFollowUpReminderSentParams struct {
	SentAt time.Time `json:"sent_at"`
	ID     uuid.UUID `json:"id"`
}

// MarkFollowUpReminderSent is flow 4 step 9, minus the resend_email_id
// assignment: no such column exists in migration 000008 or the ERD, and no
// email is sent in the MVP.
//
// The sent_at IS NULL guard makes this idempotent — a concurrent or repeated
// run updates nothing and returns no row rather than moving the timestamp.
func (q *Queries) MarkFollowUpReminderSent(ctx context.Context, arg MarkFollowUpReminderSentParams) (FollowUpReminder, error) {
	row := q.db.QueryRow(ctx, markFollowUpReminderSent, arg.SentAt, arg.ID)
	var i FollowUpReminder
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DueAt,
		&i.SentAt,
		&i.DismissedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
