// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Resolves a captured page's domain to a site row. Returns pgx.ErrNoRows when
	// the domain is not a configured site.
	GetSiteByDomain(ctx context.Context, domain string) (Site, error)
	// Returns every site the extension is currently allowed to capture from.
	ListActiveSites(ctx context.Context) ([]Site, error)
}

var _ Querier = (*Queries)(nil)
