// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, profile_summary, created_at, updated_at FROM settings
WHERE id = true
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ProfileSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfileSummary = `-- name: UpsertProfileSummary :one
INSERT INTO settings (id, profile_summary)
VALUES (true, $1)
ON CONFLICT (id) DO UPDATE
SET profile_summary = EXCLUDED.profile_summary,
    updated_at      = now()
RETURNING id, profile_summary, created_at, updated_at
`

// Upsert rather than update: if the row seeded by migration 000011 is ever
// missing, the first write puts it back instead of failing forever.
func (q *Queries) UpsertProfileSummary(ctx context.Context, profileSummary *string) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertProfileSummary, profileSummary)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ProfileSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
