// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (user_id, name, domain, is_preconfigured, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id
`

type CreateSiteParams struct {
	UserID          *uuid.UUID `json:"user_id"`
	Name            string     `json:"name"`
	Domain          string     `json:"domain"`
	IsPreconfigured bool       `json:"is_preconfigured"`
	IsActive        bool       `json:"is_active"`
}

// Always owned: a site created through this statement is never global. The
// pre-configured list is seeded exclusively through EnsureSite below.
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.UserID,
		arg.Name,
		arg.Domain,
		arg.IsPreconfigured,
		arg.IsActive,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :execrows
DELETE FROM sites
WHERE id = $1 AND user_id = $2::uuid
`

type DeleteSiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Owned rows only. The service already refuses to delete a pre-configured
// site before this runs (ErrPreconfigured), so in practice this only ever
// targets a row with user_id set — but scoping it here too means a caller
// can never delete another user's custom site by guessing its id.
// Fails with 23503 when applications still reference the site: the foreign key
// is ON DELETE RESTRICT.
func (q *Queries) DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSite, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSite = `-- name: EnsureSite :one
INSERT INTO sites (name, domain, is_preconfigured, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (domain) WHERE user_id IS NULL DO NOTHING
RETURNING id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id
`

type EnsureSiteParams struct {
	Name            string `json:"name"`
	Domain          string `json:"domain"`
	IsPreconfigured bool   `json:"is_preconfigured"`
	IsActive        bool   `json:"is_active"`
}

// Idempotent insert used to seed the pre-configured list on boot. DO NOTHING
// means no row is returned when the domain is already registered, which the
// repository reads as "nothing to do" rather than an error.
//
// Unchanged by phase 15: this always writes a global row (user_id defaults to
// NULL) and has no caller to scope to — it runs once at boot, before any
// request exists.
//
// The WHERE clause on the conflict target is load-bearing. Migration 000015
// replaced the plain unique(domain) with two rescoped constraints — one on
// (user_id, domain), and a partial unique index on (domain) that applies only
// to the global rows, where user_id IS NULL. Postgres will not infer a partial
// index as an arbiter unless the statement restates its predicate, so a bare
// ON CONFLICT (domain) matches no constraint at all and fails at runtime with
// 42P10 rather than at generate time.
//
// Note this only guards the domain constraint; name is UNIQUE too, and a
// collision there surfaces as 23505.
func (q *Queries) EnsureSite(ctx context.Context, arg EnsureSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, ensureSite,
		arg.Name,
		arg.Domain,
		arg.IsPreconfigured,
		arg.IsActive,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id FROM sites
WHERE id = $1
  AND (user_id IS NULL OR user_id = $2::uuid)
`

type GetSiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSite(ctx context.Context, arg GetSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, arg.ID, arg.UserID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id FROM sites
WHERE domain = $1
  AND (user_id IS NULL OR user_id = $2::uuid)
`

type GetSiteByDomainParams struct {
	Domain string    `json:"domain"`
	UserID uuid.UUID `json:"user_id"`
}

// Resolves a captured page's domain to a site row, global or the caller's own.
// Returns pgx.ErrNoRows when the domain is not a configured site for this user.
func (q *Queries) GetSiteByDomain(ctx context.Context, arg GetSiteByDomainParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByDomain, arg.Domain, arg.UserID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listActiveSites = `-- name: ListActiveSites :many

SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id FROM sites
WHERE is_active = true
  AND (user_id IS NULL OR user_id = $1::uuid)
ORDER BY name
`

// Phase 15: every read is scoped to "global (user_id IS NULL) or mine" — a
// pre-configured site belongs to everyone, a custom one belongs to whoever
// added it. Writes that create or remove a row are scoped to the caller alone;
// EnsureSite is the one exception, since it only ever writes global rows at
// boot and has no caller to scope to.
// Returns every site the extension is currently allowed to capture from —
// the pre-configured list plus this user's own active custom sites.
func (q *Queries) ListActiveSites(ctx context.Context, userID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listActiveSites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.IsPreconfigured,
			&i.IsActive,
			&i.Selectors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id FROM sites
WHERE user_id IS NULL OR user_id = $1::uuid
ORDER BY name
`

// Every site this user can see, active or not: the pre-configured list plus
// their own custom sites. Backs the dashboard settings page, which has to show
// the deactivated ones in order to switch them back on.
func (q *Queries) ListSites(ctx context.Context, userID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.IsPreconfigured,
			&i.IsActive,
			&i.Selectors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSiteActive = `-- name: SetSiteActive :one
UPDATE sites
SET is_active = $2
WHERE id = $1
  AND (user_id IS NULL OR user_id = $3::uuid)
RETURNING id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at, user_id
`

type SetSiteActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
	UserID   uuid.UUID `json:"user_id"`
}

// Global-or-mine, matching every other read here: a global row can be
// deactivated by any user (the ERD's own rule — "pre-configured rows can only
// be deactivated" carries no per-user override, so this remains one shared
// switch, same as before phase 15), and a custom row only by its owner.
// updated_at is maintained by trg_sites_updated_at.
func (q *Queries) SetSiteActive(ctx context.Context, arg SetSiteActiveParams) (Site, error) {
	row := q.db.QueryRow(ctx, setSiteActive, arg.ID, arg.IsActive, arg.UserID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
