// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"
)

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at FROM sites
WHERE domain = $1
`

// Resolves a captured page's domain to a site row. Returns pgx.ErrNoRows when
// the domain is not a configured site.
func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.IsPreconfigured,
		&i.IsActive,
		&i.Selectors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSites = `-- name: ListActiveSites :many
SELECT id, name, domain, is_preconfigured, is_active, selectors, created_at, updated_at FROM sites
WHERE is_active = true
ORDER BY name
`

// Returns every site the extension is currently allowed to capture from.
func (q *Queries) ListActiveSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listActiveSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.IsPreconfigured,
			&i.IsActive,
			&i.Selectors,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
